from sqlalchemy import Column,Integer,String,Boolean
from PyDialer.crud import mixin
from PyDialer.depends.db import Model
from PyDialer.schemas.pjsip import BasicEndpoint
from PyDialer.schemas import asterisk_enum as astenum


class ps_aors(mixin.CRUDMixin,Model.BaseORM):
    id = Column(String(40),primary_key=True, index=True) 
    contact = Column(String(40))  
    default_expiration = Column(Integer)  
    mailboxes = Column(String(80))  
    max_contacts = Column(Integer) 
    minimum_expiration = Column(Integer) 
    remove_existing = Column(String(20)) 
    qualify_frequency = Column(Integer) 
    authenticate_qualify = Column(String(20)) 

class ps_auth(mixin.CRUDMixin,Model.BaseORM):
    id = Column(String(40),primary_key=True, index=True) 
    auth_type = Column(String(40))  
    nonce_lifetime = Column(Integer) 
    md5_cred = Column(String(40))  
    password = Column(String(80)) 
    realm    = Column(String(40)) 
    username = Column(String(40))    

class ps_endpoint(mixin.CRUDMixin,Model.BaseORM):
    id = Column(String(40),primary_key=True, index=True) 
    transport = Column(String(40))  
    aors = Column(String(200))  
    auth = Column(String(40)) 
    context = Column(String(40)) 
    disallow = Column(String(200))  
    allow = Column(String(200)) 
    direct_media = Column(String(40))
    connected_line_method = Column(String(40))
    direct_media_method = Column(String(40))
    direct_media_glare_mitigation = Column(String(40))
    disable_direct_media_on_nat = Column(String(40)) 
    dtmf_mode = Column(String(40))
    external_media_address = Column(String(40))
    force_rport = Column(String(40))
    ice_support = Column(String(40))
    identify_by = Column(String(40))
    mailboxes = Column(String(40))
    moh_suggest = Column(String(40))
    outbound_auth = Column(String(40))
    outbound_proxy = Column(String(40))
    rewrite_contact = Column(String(40))
    rtp_ipv6 = Column(String(40))
    rtp_symmetric = Column(String(40))
    send_diversion = Column(String(40))
    send_pai = Column(String(40))
    send_rpid = Column(String(40))
    timers_min_se = Column(Integer) 
    timers  = Column(String(40)) 
    timers_sess_expires = Column(Integer) 
    callerid = Column(String(40))
    callerid_privacy  = Column(String(40)) 
    callerid_tag = Column(String(40))
    hundredrel  = Column('100rel',String(40))
    aggregate_mwi = Column(String(40))
    trust_id_inbound = Column(String(40))
    trust_id_outbound = Column(String(40))
    use_ptime = Column(String(40))
    use_avpf = Column(String(40))
    media_encryption = Column(String(40))
    inband_progress = Column(String(40))
    call_group = Column(String(40))
    pickup_group = Column(String(40))
    named_call_group = Column(String(40))
    named_pickup_group = Column(String(40))
    device_state_busy_at = Column(Integer) 
    fax_detect = Column(String(40))
    t38_udptl = Column(String(40))
    t38_udptl_ec = Column(String(40))
    t38_udptl_maxdatagram = Column(Integer) 
    t38_udptl_nat = Column(String(40))
    t38_udptl_ipv6 = Column(String(40))
    tone_zone = Column(String(40))
    language = Column(String(40))
    one_touch_recording = Column(String(40))
    record_on_feature = Column(String(40))
    record_off_feature = Column(String(40))
    rtp_engine = Column(String(40))
    allow_transfer = Column(String(40))
    allow_subscribe = Column(String(40))
    sdp_owner = Column(String(40))
    sdp_session = Column(String(40))
    tos_audio = Column(Integer) 
    tos_video = Column(Integer) 
    cos_audio = Column(Integer) 
    cos_video = Column(Integer) 
    sub_min_expiry = Column(Integer) 
    from_domain = Column(String(40))
    from_user = Column(String(40))
    mwi_fromuser = Column(String(40))
    dtls_verify = Column(String(40))
    dtls_rekey = Column(String(40))
    dtls_cert_file = Column(String(200)) 
    dtls_private_key = Column(String(200)) 
    dtls_cipher = Column(String(200)) 
    dtls_ca_file = Column(String(200)) 
    dtls_ca_path = Column(String(200)) 
    dtls_setup = Column(String(40))
    srtp_tag_32 = Column(String(40))
