
from typing import Optional
from datetime import datetime
from pydantic import BaseModel, EmailStr
from .. import asterisk_enum as asnum
from ..base import ORMBaseModel


class ps_endpoints(BaseModel):
	id:str
	transport:Optional[str] = None
	aors:Optional[str] = None
	auth:Optional[str] = None
	context:Optional[str] = None
	disallow:Optional[str] = None
	allow:Optional[str] = None
	callerid:Optional[str] = None
	dtmf_mode:Optional[asnum.pjsip_dtmf_mode_values_v3] = asnum.pjsip_dtmf_mode_values_v3.rfc4733
	rtp_keepalive:Optional[int] = None
	rtp_timeout:Optional[int] = None
	rtp_timeout_hold:Optional[int] = None	
	direct_media:Optional[asnum.yesno_values] = asnum.yesno_values.yes
	rewrite_contact:Optional[asnum.yesno_values] = asnum.yesno_values.yes
	force_rport:Optional[asnum.yesno_values] = asnum.yesno_values.yes	
	# use_avpf:Optional[asnum.yesno_values] = None
	# redirect_method:Optional[asnum.pjsip_redirect_method_values] = None
	# media_encryption:Optional[asnum.pjsip_media_encryption_values] = None
	# cos_audio:Optional[int] = None
	# cos_video:Optional[int] = None
	# inband_progress:Optional[asnum.yesno_values] = None
	# force_avp:Optional[asnum.yesno_values] = None
	# media_use_received_transport:Optional[asnum.yesno_values] = None
	# ice_support:Optional[asnum.yesno_values] = None
	# user_eq_phone:Optional[asnum.yesno_values] = None
	# moh_passthrough:Optional[asnum.yesno_values] = None
	# media_encryption_optimistic:Optional[asnum.yesno_values] = None
	# rpid_immediate:Optional[asnum.yesno_values] = None
	# g726_non_standard:Optional[asnum.yesno_values] = None
	# bind_rtp_to_media_address:Optional[asnum.yesno_values] = None
	# connected_line_method:Optional[asnum.pjsip_connected_line_method_values] = None
	# mwi_subscribe_replaces_unsolicited:Optional[asnum.ast_bool_values] = None
	# direct_media_method:Optional[asnum.pjsip_connected_line_method_values] = None
	# direct_media_glare_mitigation:Optional[asnum.pjsip_direct_media_glare_mitigation_values] = None
	# device_state_busy_at:Optional[int] = None
	# fax_detect:Optional[asnum.yesno_values] = None
	# t38_udptl:Optional[asnum.yesno_values] = None
	# t38_udptl_ec:Optional[asnum.pjsip_t38udptl_ec_values] = None
	# t38_udptl_maxdatagram:Optional[int] = None
	# fax_detect_timeout:Optional[int] = None
	# t38_udptl_nat:Optional[asnum.yesno_values] = None
	# preferred_codec_only:Optional[asnum.yesno_values] = None
	# asymmetric_rtp_codec:Optional[asnum.yesno_values] = None
	# rtcp_mux:Optional[asnum.yesno_values] = None
	# allow_overlap:Optional[asnum.yesno_values] = asnum.yesno_values.yes
	# refer_blind_progress:Optional[asnum.yesno_values] = None
	# notify_early_inuse_ringing:Optional[asnum.yesno_values] = None
	# max_audio_streams:Optional[int] = None
	# max_video_streams:Optional[int] = None
	# webrtc:Optional[asnum.yesno_values] = None
	# dtls_fingerprint:Optional[asnum.sha_hash_values] = None
	# t38_udptl_ipv6:Optional[asnum.yesno_values] = None
	# bundle:Optional[asnum.yesno_values] = None
	# dtls_auto_generate_cert:Optional[asnum.yesno_values] = None
	# follow_early_media_fork:Optional[asnum.yesno_values] = None
	# accept_multiple_sdp_answers:Optional[asnum.yesno_values] = asnum.yesno_values.no
	# suppress_q850_reason_headers:Optional[asnum.yesno_values] = None
	# trust_connected_line:Optional[asnum.ast_bool_values] = None
	# send_connected_line:Optional[asnum.ast_bool_values] = None
	# ignore_183_without_sdp:Optional[asnum.ast_bool_values] = None
	# disable_direct_media_on_nat:Optional[asnum.yesno_values] = None

	# one_touch_recording:Optional[asnum.yesno_values] = None
	# stir_shaken:Optional[asnum.ast_bool_values] = None
	# send_history_info:Optional[asnum.ast_bool_values] = None
	# allow_unauthenticated_options:Optional[asnum.ast_bool_values] = None
	# t38_bind_udptl_to_media_address:Optional[asnum.ast_bool_values] = None
	# rtp_ipv6:Optional[asnum.yesno_values] = None
	# rtp_symmetric:Optional[asnum.yesno_values] = None
	# allow_transfer:Optional[asnum.yesno_values] = None
	# allow_subscribe:Optional[asnum.yesno_values] = None
	# send_diversion:Optional[asnum.yesno_values] = None
	# send_pai:Optional[asnum.yesno_values] = None
	# send_rpid:Optional[asnum.yesno_values] = None
	# timers_min_se:Optional[int] = None
	# sub_min_expiry:Optional[int] = None
	# timers:Optional[asnum.pjsip_timer_values] = None
	# timers_sess_expires:Optional[int] = None
	# callerid_privacy:Optional[asnum.pjsip_cid_privacy_values] = None
	# hundredrel:Optional[asnum.pjsip_100rel_values] = asnum.pjsip_100rel_values.yes
	# aggregate_mwi:Optional[asnum.yesno_values] = asnum.yesno_values.yes
	# trust_id_inbound:Optional[asnum.yesno_values] = None
	# trust_id_outbound:Optional[asnum.yesno_values] = None
	# use_ptime:Optional[asnum.yesno_values] = None
	# dtls_setup:Optional[asnum.pjsip_dtls_setup_values] = None
	# srtp_tag_32:Optional[asnum.yesno_values] = None
	# geoloc_outgoing_call_profile:Optional[str] = None
	# external_media_address:Optional[str] = None
	# identify_by:Optional[str] = None
	# mailboxes:Optional[str] = None
	# moh_suggest:Optional[str] = None
	# outbound_auth:Optional[str] = None
	# outbound_proxy:Optional[str] = None
	# callerid_tag:Optional[str] = None
	# call_group:Optional[str] = None
	# pickup_group:Optional[str] = None
	# named_call_group:Optional[str] = None
	# named_pickup_group:Optional[str] = None
	# tone_zone:Optional[str] = None
	# language:Optional[str] = None
	# record_on_feature:Optional[str] = None
	# record_off_feature:Optional[str] = None
	# rtp_engine:Optional[str] = None
	# sdp_owner:Optional[str] = None
	# sdp_session:Optional[str] = None
	# tos_audio:Optional[str] = None
	# tos_video:Optional[str] = None
	# from_domain:Optional[str] = None
	# from_user:Optional[str] = None
	# mwi_from_user:Optional[str] = None
	# dtls_verify:Optional[str] = None
	# dtls_rekey:Optional[str] = None
	# dtls_cert_file:Optional[str] = None
	# dtls_private_key:Optional[str] = None
	# dtls_cipher:Optional[str] = None
	# dtls_ca_file:Optional[str] = None
	# dtls_ca_path:Optional[str] = None
	# media_address:Optional[str] = None
	# set_var:Optional[str] = None
	# message_context:Optional[str] = None
	# accountcode:Optional[str] = None
	# voicemail_extension:Optional[str] = None
	# deny:Optional[str] = None
	# permit:Optional[str] = None
	# acl:Optional[str] = None
	# contact_deny:Optional[str] = None
	# contact_permit:Optional[str] = None
	# contact_acl:Optional[str] = None
	# subscribe_context:Optional[str] = None
	# contact_user:Optional[str] = None
	# incoming_mwi_mailbox:Optional[str] = None
	# codec_prefs_incoming_offer:Optional[str] = None
	# codec_prefs_outgoing_offer:Optional[str] = None
	# codec_prefs_incoming_answer:Optional[str] = None
	# codec_prefs_outgoing_answer:Optional[str] = None
	# geoloc_incoming_call_profile:Optional[str] = None
