"""user model updated

Revision ID: 534fc96cb93d
Revises: 0b7264cb1f50
Create Date: 2022-12-22 00:10:01.371968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534fc96cb93d'
down_revision = '0b7264cb1f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
