"""user group model

Revision ID: 833e65080daa
Revises: 24aec71593c1
Create Date: 2022-12-27 16:47:03.680089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833e65080daa'
down_revision = '24aec71593c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usergroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'group_id')
    )
    op.drop_constraint('user_group_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_group_id_fkey', 'user', 'groups', ['group_id'], ['id'])
    op.drop_table('usergroup')
    # ### end Alembic commands ###
