"""user group model

Revision ID: a1cab3bde5d1
Revises: ef06c36f7a55
Create Date: 2022-12-27 09:01:07.898135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cab3bde5d1'
down_revision = 'ef06c36f7a55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_group_id_fkey', 'user', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_group_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    op.drop_table('groups')
    # ### end Alembic commands ###
