"""user agent relation

Revision ID: b17c8032f6cb
Revises: 534fc96cb93d
Create Date: 2022-12-24 16:54:11.764158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17c8032f6cb'
down_revision = '534fc96cb93d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userendpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['ps_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userendpoint')
    # ### end Alembic commands ###
