"""second migration

Revision ID: d87cf32311d5
Revises: 8b5db12ac884
Create Date: 2022-12-05 23:43:48.374063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87cf32311d5'
down_revision = '8b5db12ac884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
