"""user details update

Revision ID: ef06c36f7a55
Revises: b17c8032f6cb
Create Date: 2022-12-24 18:05:17.700704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef06c36f7a55'
down_revision = 'b17c8032f6cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=127), nullable=False,server_default='me'))
    op.alter_column('user', 'name', server_default=None)
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'userendpoint', ['endpoint_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userendpoint_endpoint_id_key', 'userendpoint', type_='unique')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
