
from sqlalchemy import (
	Column,Integer,BigInteger,
	TIMESTAMP,String,FLOAT,TEXT,
	NUMERIC,UniqueConstraint,LargeBinary
	)
from PyDialer.crud import mixin
from PyDialer.depends.db import Model
from PyDialer.schemas.asterisk_enum import *


class queues(mixin.CRUDMixin,Model.BaseORM):
	timeout = Column('timeout',Integer)
	ringinuse = Column('ringinuse',Sql_yesno_values)
	announce_position_limit = Column('announce_position_limit',Integer)
	setinterfacevar = Column('setinterfacevar',Sql_yesno_values)
	periodic_announce_frequency = Column('periodic_announce_frequency',Integer)
	relative_periodic_announce = Column('relative_periodic_announce',Sql_yesno_values)
	random_periodic_announce = Column('random_periodic_announce',Sql_yesno_values)
	retry = Column('retry',Integer)
	wrapuptime = Column('wrapuptime',Integer)
	penaltymemberslimit = Column('penaltymemberslimit',Integer)
	autofill = Column('autofill',Sql_yesno_values)
	setqueuevar = Column('setqueuevar',Sql_yesno_values)
	autopause = Column('autopause',Sql_queue_autopause_values)
	autopausedelay = Column('autopausedelay',Integer)
	autopausebusy = Column('autopausebusy',Sql_yesno_values)
	autopauseunavail = Column('autopauseunavail',Sql_yesno_values)
	maxlen = Column('maxlen',Integer)
	servicelevel = Column('servicelevel',Integer)
	strategy = Column('strategy',Sql_queue_strategy_values)
	setqueueentryvar = Column('setqueueentryvar',Sql_yesno_values)
	announce_frequency = Column('announce_frequency',Integer)
	reportholdtime = Column('reportholdtime',Sql_yesno_values)
	memberdelay = Column('memberdelay',Integer)
	weight = Column('weight',Integer)
	timeoutrestart = Column('timeoutrestart',Sql_yesno_values)
	announce_to_first_user = Column('announce_to_first_user',Sql_yesno_values)
	min_announce_frequency = Column('min_announce_frequency',Integer)
	announce_round_seconds = Column('announce_round_seconds',Integer)
	timeoutpriority = Column('timeoutpriority',String(128))
	musiconhold = Column('musiconhold',String(128))
	announce = Column('announce',String(128))
	context = Column('context',String(128))
	monitor_format = Column('monitor_format',String(8))
	membermacro = Column('membermacro',String(512))
	membergosub = Column('membergosub',String(512))
	queue_youarenext = Column('queue_youarenext',String(128))
	queue_thereare = Column('queue_thereare',String(128))
	queue_callswaiting = Column('queue_callswaiting',String(128))
	queue_quantity1 = Column('queue_quantity1',String(128))
	queue_quantity2 = Column('queue_quantity2',String(128))
	queue_holdtime = Column('queue_holdtime',String(128))
	queue_minutes = Column('queue_minutes',String(128))
	queue_minute = Column('queue_minute',String(128))
	queue_seconds = Column('queue_seconds',String(128))
	queue_thankyou = Column('queue_thankyou',String(128))
	queue_callerannounce = Column('queue_callerannounce',String(128))
	queue_reporthold = Column('queue_reporthold',String(128))
	announce_holdtime = Column('announce_holdtime',String(128))
	announce_position = Column('announce_position',String(128))
	periodic_announce = Column('periodic_announce',String(50))
	monitor_type = Column('monitor_type',String(128))
	joinempty = Column('joinempty',String(128))
	leavewhenempty = Column('leavewhenempty',String(128))
	defaultrule = Column('defaultrule',String(128))
	name = Column('name',String(128),nullable=False)
