
from sqlalchemy import (
	Column,Integer,BigInteger,
	TIMESTAMP,String,FLOAT,TEXT,
	NUMERIC,UniqueConstraint,LargeBinary
	)
from PyDialer.crud import mixin
from PyDialer.depends.db import Model
from PyDialer.schemas.asterisk_enum import *


class sippeers(mixin.CRUDMixin,Model.BaseORM):
	supportpath = Column('supportpath',Sql_yes_no_values)
	port = Column('port',Integer)
	regseconds = Column('regseconds',Integer)
	lastms = Column('lastms',Integer)
	type = Column('type',Sql_type_values)
	transport = Column('transport',Sql_sip_transport_values)
	dtmfmode = Column('dtmfmode',Sql_sip_dtmfmode_values)
	directmedia = Column('directmedia',Sql_sip_directmedia_values_v2)
	trustrpid = Column('trustrpid',Sql_yes_no_values)
	progressinband = Column('progressinband',Sql_sip_progressinband_values)
	promiscredir = Column('promiscredir',Sql_yes_no_values)
	useclientcode = Column('useclientcode',Sql_yes_no_values)
	callcounter = Column('callcounter',Sql_yes_no_values)
	busylevel = Column('busylevel',Integer)
	allowoverlap = Column('allowoverlap',Sql_yes_no_values)
	allowsubscribe = Column('allowsubscribe',Sql_yes_no_values)
	videosupport = Column('videosupport',Sql_yes_no_values)
	maxcallbitrate = Column('maxcallbitrate',Integer)
	rfc2833compensate = Column('rfc2833compensate',Sql_yes_no_values)
	session-timers = Column('session-timers',Sql_sip_session_timers_values)
	session-expires = Column('session-expires',Integer)
	session-minse = Column('session-minse',Integer)
	session-refresher = Column('session-refresher',Sql_sip_session_refresher_values)
	rtptimeout = Column('rtptimeout',Integer)
	rtpholdtimeout = Column('rtpholdtimeout',Integer)
	sendrpid = Column('sendrpid',Sql_yes_no_values)
	timert1 = Column('timert1',Integer)
	timerb = Column('timerb',Integer)
	qualifyfreq = Column('qualifyfreq',Integer)
	constantssrc = Column('constantssrc',Sql_yes_no_values)
	usereqphone = Column('usereqphone',Sql_yes_no_values)
	textsupport = Column('textsupport',Sql_yes_no_values)
	faxdetect = Column('faxdetect',Sql_yes_no_values)
	buggymwi = Column('buggymwi',Sql_yes_no_values)
	callingpres = Column('callingpres',Sql_sip_callingpres_values)
	hasvoicemail = Column('hasvoicemail',Sql_yes_no_values)
	subscribemwi = Column('subscribemwi',Sql_yes_no_values)
	autoframing = Column('autoframing',Sql_yes_no_values)
	rtpkeepalive = Column('rtpkeepalive',Integer)
	call-limit = Column('call-limit',Integer)
	g726nonstandard = Column('g726nonstandard',Sql_yes_no_values)
	ignoresdpversion = Column('ignoresdpversion',Sql_yes_no_values)
	allowtransfer = Column('allowtransfer',Sql_yes_no_values)
	dynamic = Column('dynamic',Sql_yes_no_values)
	id = Column('id',Integer,nullable=False)
	name = Column('name',String(40),nullable=False)
	ipaddr = Column('ipaddr',String(45))
	contactdeny = Column('contactdeny',String(95))
	mohinterpret = Column('mohinterpret',String(40))
	defaultuser = Column('defaultuser',String(40))
	fullcontact = Column('fullcontact',String(80))
	regserver = Column('regserver',String(20))
	useragent = Column('useragent',String(255))
	mohsuggest = Column('mohsuggest',String(40))
	host = Column('host',String(40))
	t38pt_usertpsource = Column('t38pt_usertpsource',String(40))
	context = Column('context',String(40))
	permit = Column('permit',String(95))
	deny = Column('deny',String(95))
	secret = Column('secret',String(40))
	md5secret = Column('md5secret',String(40))
	remotesecret = Column('remotesecret',String(40))
	regexten = Column('regexten',String(40))
	fromdomain = Column('fromdomain',String(40))
	fromuser = Column('fromuser',String(40))
	nat = Column('nat',String(29))
	callgroup = Column('callgroup',String(40))
	pickupgroup = Column('pickupgroup',String(40))
	language = Column('language',String(40))
	disallow = Column('disallow',String(200))
	allow = Column('allow',String(200))
	insecure = Column('insecure',String(40))
	qualify = Column('qualify',String(40))
	defaultip = Column('defaultip',String(45))
	parkinglot = Column('parkinglot',String(40))
	vmexten = Column('vmexten',String(40))
	accountcode = Column('accountcode',String(80))
	setvar = Column('setvar',String(200))
	callerid = Column('callerid',String(40))
	amaflags = Column('amaflags',String(40))
	auth = Column('auth',String(40))
	outboundproxy = Column('outboundproxy',String(40))
	callbackextension = Column('callbackextension',String(40))
	fullname = Column('fullname',String(40))
	trunkname = Column('trunkname',String(40))
	cid_number = Column('cid_number',String(40))
	path = Column('path',String(256))
	mailbox = Column('mailbox',String(40))
	contactpermit = Column('contactpermit',String(95))
